# Generated by Django 4.1.4 on 2023-10-29 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 29, 23, 34, 35, 294181, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
