# Generated by Django 4.1.4 on 2024-01-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elo", "0003_frame_breaking_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
